# Generated by Django 6.0.3 on 2026-04-04 03:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('calories', models.PositiveIntegerField(default=2000)),
                ('protein_g', models.PositiveIntegerField(default=150)),
                ('carbs_g', models.PositiveIntegerField(default=200)),
                ('fat_g', models.PositiveIntegerField(default=65)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('USDA', 'USDA'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=10)),
                ('usda_fdc_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('serving_grams', models.DecimalField(decimal_places=1, max_digits=8)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], default='SNACK', max_length=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='tracker.fooditem')),
            ],
            options={
                'ordering': ['meal_type', 'logged_at'],
            },
        ),
    ]
